<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\agent\EePulse.Agent.Core\EePulse.Agent.Core.csproj" />
    <ProjectReference Include="..\..\src\agent\EePulse.Agent.Infrastructure\EePulse.Agent.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\backend\EePulse.Contracts\EePulse.Contracts.csproj" />
  </ItemGroup>
</Project>
